In [0]:
import numpy as np

In [0]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1

arr1[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23],
       [26, 28],
       [31, 33],
       [36, 38]])

In [0]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 

arr1[::3,::2]

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [11]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 10000

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[8464, 9265, 7228, 3538, 7325],
       [1676, 3952, 7236, 2878, 6217]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
np.percentile(arr1,25)

9.75

In [0]:
# Q3. Write a code to normalize arr2.
t=arr2.shape
for i in range(t[0]):
  a=min(arr2[i])
  b=max(arr2[i])
  for j in range(t[1]) :
    arr2[i][j]=(arr2[i][j]-a)/(b-a)
arr2

array([[0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [17]:
arr2=(arr2-arr2.min())/(arr2.max()-arr2.min())
arr2

array([[0.8944525 , 1.        , 0.73158519, 0.24535512, 0.74436685],
       [0.        , 0.29990776, 0.73263935, 0.15838714, 0.59836606]])

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [0]:
# Q4. How would you check if your numpy array has some missing values?

x = np.array([1.0, 2.5, np.nan, 1.3, np.inf, 7.2])
print("input array with bad values:")
print(x)

xm = np.ma.masked_invalid(x)
print("masked version:")
print(xm)

diff=len(x)-xm.count()

print("{} missing values".format(diff))


# Hint: Thoda research karo numpy me existing functions hai

# I have taken help from this page :
# https://currents.soest.hawaii.edu/ocn_data_analysis/_static/masked_arrays.html

input array with bad values:
[1.  2.5 nan 1.3 inf 7.2]
masked version:
[1.0 2.5 -- 1.3 -- 7.2]
2 missing values


In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [0]:
def findValue(arr,n) :
  return sorted(arr)[-n]

val=findValue(np.array([12,34,40,7,1,0]),1)
print(val)

40
